
services:
  fensterkontakt:
    build: fensterkontakt
    container_name: fensterkontakt
    ports:
      - "3001:3001"
    networks:
      - smartHome

  smarthome:
    build: smarthome
    container_name: smarthome
    ports:
      - "3000:3000"
    networks:
      - smartHome

  thermostat:
    build: thermostat
    container_name: thermostat
    ports:
      - "3002:3002"
    networks:
      - smartHome

  webinterface:
    build: webinterface
    container_name: webinterface
    ports:
      - "8080:8080"
    networks:
      - smartHome

networks:
  smartHome:
    driver: bridge
